export interface Question {
  id: number;
  question: string;
  options: string[];
  correct: number;
  explanation: string;
  category: string;
}

export const cricketQuestions: Question[] = [
  {
    id: 1,
    question: "Who holds the record for the highest individual score in Test cricket?",
    options: ["Brian Lara", "Sachin Tendulkar", "Matthew Hayden", "Len Hutton"],
    correct: 0,
    explanation: "Brian Lara scored 400* against England in 2004, the highest individual score in Test cricket.",
    category: "Records",
  },
  {
    id: 2,
    question: "Which country won the first Cricket World Cup in 1975?",
    options: ["Australia", "India", "West Indies", "England"],
    correct: 2,
    explanation: "West Indies won the inaugural Cricket World Cup in 1975, defeating Australia in the final.",
    category: "World Cup",
  },
  {
    id: 3,
    question: "Who is the highest run-scorer in international cricket?",
    options: ["Ricky Ponting", "Sachin Tendulkar", "Kumar Sangakkara", "Jacques Kallis"],
    correct: 1,
    explanation: "Sachin Tendulkar holds the record with 34,357 runs across all international formats.",
    category: "Records",
  },
  {
    id: 4,
    question: "What is the maximum number of overs in a One Day International (ODI)?",
    options: ["40", "45", "50", "60"],
    correct: 2,
    explanation: "ODIs are played over 50 overs per side, introduced in the 1970s.",
    category: "Rules",
  },
  {
    id: 5,
    question: "Which bowler has taken the most wickets in Test cricket?",
    options: ["Shane Warne", "Muttiah Muralitharan", "Anil Kumble", "Glenn McGrath"],
    correct: 1,
    explanation: "Muttiah Muralitharan took 800 wickets in Test cricket, the all-time record.",
    category: "Records",
  },
  {
    id: 6,
    question: "In which year did India win their first Cricket World Cup?",
    options: ["1979", "1983", "1987", "1992"],
    correct: 1,
    explanation: "India won their first Cricket World Cup in 1983 under Kapil Dev's captaincy.",
    category: "World Cup",
  },
  {
    id: 7,
    question: "What does 'LBW' stand for in cricket?",
    options: ["Left Behind Wicket", "Leg Before Wicket", "Low Ball Wide", "Left Bat Wide"],
    correct: 1,
    explanation: "LBW stands for Leg Before Wicket — when the ball hits the batsman's leg before the bat.",
    category: "Rules",
  },
  {
    id: 8,
    question: "Who scored the first double century in ODI cricket?",
    options: ["Virender Sehwag", "Sachin Tendulkar", "Rohit Sharma", "Martin Guptill"],
    correct: 1,
    explanation: "Sachin Tendulkar scored 200* against South Africa in 2010, the first double century in ODIs.",
    category: "Records",
  },
  {
    id: 9,
    question: "Which stadium is known as the 'Home of Cricket'?",
    options: ["Eden Gardens", "MCG", "Lord's Cricket Ground", "Wankhede Stadium"],
    correct: 2,
    explanation: "Lord's Cricket Ground in London is known as the 'Home of Cricket' and is the oldest cricket ground.",
    category: "Venues",
  },
  {
    id: 10,
    question: "How many balls are in a standard cricket over?",
    options: ["4", "5", "6", "8"],
    correct: 2,
    explanation: "A standard cricket over consists of 6 balls bowled by the same bowler.",
    category: "Rules",
  },
  {
    id: 11,
    question: "Who is known as the 'God of Cricket'?",
    options: ["Virat Kohli", "Sachin Tendulkar", "Brian Lara", "Don Bradman"],
    correct: 1,
    explanation: "Sachin Tendulkar is widely known as the 'God of Cricket' for his extraordinary achievements.",
    category: "Players",
  },
  {
    id: 12,
    question: "What is the highest partnership in Test cricket?",
    options: ["576 runs", "624 runs", "664 runs", "712 runs"],
    correct: 0,
    explanation: "The highest partnership in Test cricket is 576 runs between Kumar Sangakkara and Mahela Jayawardene.",
    category: "Records",
  },
  {
    id: 13,
    question: "Which country invented the game of cricket?",
    options: ["India", "Australia", "England", "South Africa"],
    correct: 2,
    explanation: "Cricket originated in England in the 16th century and was spread globally by the British Empire.",
    category: "History",
  },
  {
    id: 14,
    question: "What is a 'hat-trick' in cricket?",
    options: [
      "Three sixes in a row",
      "Three wickets in three consecutive balls",
      "Three fours in an over",
      "Scoring 100 runs in 100 balls",
    ],
    correct: 1,
    explanation: "A hat-trick occurs when a bowler takes three wickets with three consecutive deliveries.",
    category: "Rules",
  },
  {
    id: 15,
    question: "Who has scored the most centuries in international cricket?",
    options: ["Ricky Ponting", "Sachin Tendulkar", "Virat Kohli", "Kumar Sangakkara"],
    correct: 1,
    explanation: "Sachin Tendulkar holds the record with 100 international centuries (51 Tests + 49 ODIs).",
    category: "Records",
  },
  {
    id: 16,
    question: "In T20 cricket, how many overs does each team bat?",
    options: ["10", "15", "20", "25"],
    correct: 2,
    explanation: "In T20 cricket, each team bats for a maximum of 20 overs.",
    category: "Rules",
  },
  {
    id: 17,
    question: "Who captained India to their 2011 World Cup victory?",
    options: ["Sourav Ganguly", "Rahul Dravid", "MS Dhoni", "Virat Kohli"],
    correct: 2,
    explanation: "MS Dhoni captained India to their second World Cup victory in 2011 on home soil.",
    category: "World Cup",
  },
  {
    id: 18,
    question: "What is the term for a batsman scoring zero runs?",
    options: ["Blob", "Duck", "Goose egg", "Zero"],
    correct: 1,
    explanation: "A score of zero runs by a batsman is called a 'duck' in cricket.",
    category: "Terminology",
  },
  {
    id: 19,
    question: "Which cricketer is known as the 'Little Master'?",
    options: ["Sunil Gavaskar", "Sachin Tendulkar", "Gundappa Viswanath", "Dilip Vengsarkar"],
    correct: 0,
    explanation: "Sunil Gavaskar is known as the 'Little Master' for his technical brilliance and small stature.",
    category: "Players",
  },
  {
    id: 20,
    question: "What is the highest team score in a single Test innings?",
    options: ["952/6", "903/7", "849/9", "790/3"],
    correct: 1,
    explanation: "England scored 903/7 declared against Australia in 1938, the highest team score in Test cricket.",
    category: "Records",
  },
  {
    id: 21,
    question: "Who holds the record for the fastest century in ODI cricket?",
    options: ["AB de Villiers", "Shahid Afridi", "Chris Gayle", "Virender Sehwag"],
    correct: 0,
    explanation: "AB de Villiers scored the fastest ODI century in just 31 balls against West Indies in 2015.",
    category: "Records",
  },
  {
    id: 22,
    question: "What is the 'Duckworth-Lewis method' used for?",
    options: [
      "Calculating bowling speed",
      "Adjusting targets in rain-affected matches",
      "Determining pitch quality",
      "Measuring bat dimensions",
    ],
    correct: 1,
    explanation: "The Duckworth-Lewis-Stern method is used to calculate revised targets in rain-interrupted matches.",
    category: "Rules",
  },
  {
    id: 23,
    question: "Which team has won the most Cricket World Cups?",
    options: ["India", "West Indies", "Australia", "England"],
    correct: 2,
    explanation: "Australia has won the most Cricket World Cups with 6 titles (1987, 1999, 2003, 2007, 2015, 2023).",
    category: "World Cup",
  },
  {
    id: 24,
    question: "What is the term for hitting the ball over the boundary without it bouncing?",
    options: ["Four", "Six", "Boundary", "Maximum"],
    correct: 1,
    explanation: "Hitting the ball over the boundary rope without bouncing scores 6 runs and is called a 'six'.",
    category: "Rules",
  },
  {
    id: 25,
    question: "Who is the fastest bowler to take 300 Test wickets?",
    options: ["Dale Steyn", "Wasim Akram", "Malcolm Marshall", "Curtly Ambrose"],
    correct: 0,
    explanation: "Dale Steyn reached 300 Test wickets in the fewest matches (56), making him the fastest to this milestone.",
    category: "Records",
  },
  {
    id: 26,
    question: "In which city is the Eden Gardens cricket stadium located?",
    options: ["Mumbai", "Delhi", "Kolkata", "Chennai"],
    correct: 2,
    explanation: "Eden Gardens is located in Kolkata and is one of the largest cricket stadiums in the world.",
    category: "Venues",
  },
  {
    id: 27,
    question: "What is a 'maiden over' in cricket?",
    options: [
      "An over with no runs scored",
      "An over with a wicket",
      "The first over of the match",
      "An over with all dot balls and a wicket",
    ],
    correct: 0,
    explanation: "A maiden over is an over in which no runs are scored off the bat (extras may still be conceded).",
    category: "Terminology",
  },
  {
    id: 28,
    question: "Who scored the highest individual score in ODI cricket?",
    options: ["Sachin Tendulkar", "Rohit Sharma", "Martin Guptill", "Chris Gayle"],
    correct: 1,
    explanation: "Rohit Sharma holds the record for the highest ODI score with 264 runs against Sri Lanka in 2014.",
    category: "Records",
  },
  {
    id: 29,
    question: "What is the 'Ashes' series contested between?",
    options: [
      "India and Pakistan",
      "England and Australia",
      "West Indies and England",
      "South Africa and Australia",
    ],
    correct: 1,
    explanation: "The Ashes is a historic Test cricket series contested between England and Australia since 1882.",
    category: "History",
  },
  {
    id: 30,
    question: "Which Indian cricketer is known as 'The Wall'?",
    options: ["VVS Laxman", "Sourav Ganguly", "Rahul Dravid", "Anil Kumble"],
    correct: 2,
    explanation: "Rahul Dravid is known as 'The Wall' for his solid defensive technique and reliability as a batsman.",
    category: "Players",
  },
];
